import Head from 'next/head'
import About from '../Components/About/About'
import NavBar from "../Components/NavBar/NavBar"
import PrincipalPage from '../Components/PrincipalPage/PrincipalPage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ivix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <NavBar/>
          <PrincipalPage/>
          <About/>
        </div>
      </main>
    </>
  )
}
